type TFunction = (t: string) => string;
export declare function isValidKubernetesResourceName(value: string, _item: unknown, t?: TFunction): string | undefined;
export declare function isValidKubernetesResourceNameRFC1123(value: string, _item: unknown, t?: TFunction): string | undefined;
export declare function isValidKubernetesResourceNameRFC1135(value: string, _item: unknown, t?: TFunction): string | undefined;
export declare function validatePublicSshKey(value: string, t: TFunction): string | undefined;
export declare function validatePrivateSshKey(value: string, t: TFunction, requireNewline?: boolean): string | undefined;
export declare function validateCertificate(value: string, t: TFunction): string | undefined;
export declare function validateGCProjectID(value: string, t: TFunction): string | undefined;
export declare function validateJSON(value: string, t: TFunction): string | undefined;
export declare function validateBaseDnsName(value: string, t: TFunction): string | undefined;
export declare function validateLibvirtURI(value: string, t: TFunction): string | undefined;
export declare function validateImageMirror(value: string, t: TFunction): string | undefined;
export declare function validateBaseDomain(value: string, t: TFunction): string | undefined;
export declare function validateCloudsYaml(yamlValue: string, cloudValue: string, t: TFunction): string | undefined;
export declare function validateBareMetalOSImageURL(value: string, t: TFunction): string | undefined;
export declare function validateWebURL(url: string, _item: unknown, t?: TFunction): string | undefined;
export declare function validateImageContentSources(value: string, t: TFunction): string | undefined;
export declare function validateHttpProxy(value: string, t: TFunction): string | undefined;
export declare function validateHttpsProxy(value: string, t: TFunction): string | undefined;
export declare function validateNoProxy(value: string, t: TFunction): string | undefined;
export declare function validatePolicyName(value: string, resource: unknown, t?: TFunction): string | undefined;
export {};
